### PR TITLE
Upgrade globby

### PR DESCRIPTION
**Pull request by ssbarnea**
Warning: it no longer compiles, breaking mocha. NEED HELP!

### CODE REVIEW

**Comment by priyamsahoo** [comment]
@ssbarnea, after upgrading the `globby` package, you need to change the import statement to:
```import { globby } from "globby";```.

Try compiling after this, it should work.

**Comment by tomaciazek** [comment]
> @ssbarnea, after upgrading the `globby` package, you need to change the import statement to: `import { globby } from "globby";`.
> 
> Try compiling after this, it should work.

TypeScript will still compile it down to a `require` and it'll still not work - I've recently hit that issue too. You could do something like that:
```typescript
globby = await (Function('return import("globby")')() as Promise<
        typeof import('globby')
      >);
```
... or you can skip upgrading this dependency, or use something else. There is some ESM interop support coming into TypeScript, but for now it's available only in the nightly builds.

More info:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
https://github.com/microsoft/TypeScript/issues/43329#issuecomment-922544562

**Comment by priyamsahoo** [comment]
> > @ssbarnea, after upgrading the `globby` package, you need to change the import statement to: `import { globby } from "globby";`.
> > Try compiling after this, it should work.
> 
> TypeScript will still compile it down to a `require` and it'll still not work - I've recently hit that issue too. You could do something like that:
> 
> ```ts
> globby = await (Function('return import("globby")')() as Promise<
>         typeof import('globby')
>       >);
> ```
> 
> ... or you can skip upgrading this dependency, or use something else. There is some ESM interop support coming into TypeScript, but for now it's available only in the nightly builds.
> 
> More info: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c [microsoft/TypeScript#43329 (comment)](https://github.com/microsoft/TypeScript/issues/43329#issuecomment-1008361973)

Using the import statement works, i.e., it compiles successfully but at the same time it is breaking some functionality in the tests. You can check the CI.

**Comment by ssbarnea** [comment]
@tomaciazek I tried your approach but it still messes mocha run. If you know how to make it work, feel free to update this pull request (any core can edit update other PR, and do git pushes).

It would be good for us to be able to upgrade dependencies, especially for security reasons (as is less likely to need bleeding edge feature from globby). Still, I would hate to see us affected by a security issue and not to be able to quickly address it.

**Comment by tomaciazek** [comment]
> If you know how to make it work, feel free to update this pull request (any core can edit update other PR, and do git pushes).

Done :)

**Review by priyamsahoo — APPROVED** [review]
Thanks for work, @tomaciazek :)

**Pull request merged**
