### PR TITLE
Added Dockerfile and updated README.md

### PR DESCRIPTION
**Pull request by hhue13**
Not sure that PR is ready for merging as my `task default`fails locally at the moment with the following error:

`
[hhuebler@hhuelinux2 ansible-language-server]$ task -v
task: dynamic variable: 'echo "${VIRTUAL_ENV:-out/venvs/${HOSTNAME:-localhost}}"' result: 'out/venvs/hhuelinux2.hhue.at'
task: dynamic variable: 'echo ${HOSTNAME:-localhost}' result: 'hhuelinux2.hhue.at'
task: dynamic variable: 'node -p "require('./package.json').version"' result: '1.0.2'
task: "default" started
task: "setup" started
task: Task "setup" is up to date
task: [default] bash -c '[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm";
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --silent;
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh";
 nvm install'
No .nvmrc file found

Node Version Manager (v0.39.2)
:
:
`
Node.js is installed on my dev system:
`
[hhuebler@hhuelinux2 ansible-language-server]$ node
Welcome to Node.js v14.20.1.
`

I don't think that's related to my change I'd like to add but would appreciate any advise how I can get the `task` working. Thanks

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
I am afraid that building a container with the language service is outside the scope of our project at this moment. That looks to me more as something that should be the role of the consumer.

We might want to consider including it inside creator-ee, still I do not see a clear reason for adding the docker image here, especially an untested file.

**Comment by hhue13** [comment]
Hello @ssbarnea , well not adding an image to the project at all, I just wanted to add a Dockerfile allowing the consumer to build his own image (as I find the image approach as used by the yaml-language-server quite handy). Should help other consumers to to create an image from the language server if needed. 

Well I can't see that the tests fail in the code I've modified but would appreciate and hints on why these are failing nevertheless.

**Comment by ssbarnea** [comment]
Tests are failing for different reasons. FYT, I will check with others from the team become making a decision on that, but it might take till January due many being already in vacation.

**Comment by hhue13** [comment]
> Tests are failing for different reasons. FYT, I will also check with others from the team become making a decision on that, but it might take till January due many being already in vacation.

Thanks for checking! Have a Merry Xmas and a Happy New Year!

Anything I can do in the meanwhile to improve my PR?

**Comment by dcunited001** [comment]
:+1: you're doing god's work

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Please use `Containerfile` name instead of `Dockerfile`, same as we do on https://github.com/ansible/creator-ee/blob/main/Containerfile

**Comment by priyamsahoo** [comment]
@hhue13, could you please provide some use cases for why someone would need to spin up a container for the language server?

**Comment by ganeshrn** [comment]
@hhue13 Can you please rebase the PR? Also how are you using the language-server within container?

**Comment by dcunited001** [comment]
@hhue13 @ganeshrn @priyamsahoo i'm not sure if this project is compatible with [emacs-lsp/lsp-docker](https://github.com/emacs-lsp/lsp-docker) -- LSP Docker makes satisfying editor dependencies without a Gordian Knot of pyenv/npm dependencies quite a bit easier -- esp on Nix & Guix. 

At least, it would the way my system(s) and profiles are set up anyways:

- I avoid things like prettify that introduce unnecessary dependencies. ClangD is one of the few large dependencies I add to `$PATH`, since it's versatile: it formats [C/C++/Obj-C, Java, JS/TS/JSON and Protobuf](https://clang.llvm.org/docs/ClangFormat.html). 
- If I want to inject python/node/somelang LSP or Formatter, then I can do so in its project dependencies, or by injecting into `$PATH` via `direnv`. In Emacs, this is supported transparently with `envrc.el`. 
- if i want to run code, then i either run from docker or natively. however, Guix/Nix can exhibit some issues with running node binaries installed via nvm or python binaries installed via pyenv.
- LSP is one of those things I need badly that I would love to have on the network just for autocomplete (but I believe it needs file access; I've never gotten a clear answer from anyone on that).
- And I just avoid npm/node entirely if I can. 

It's ummm not exactly a standard setup, but the benefits to Nix/Guix are amazing.

The way I'm getting around lacking LSP for Ansible is just to generate snippets with [memoryleak/AdvancedAnsibleSnippetGenerator](https://github.com/memoryleak/AdvancedAnsibleSnippetsGenerator). This uses reflection on AnsibleDoc to build the examples provided by `ansible-doc -t module -s pfsensible.core.pfsense_aggregate` as Sublime snippets, which can then be converted to `yasnippet` with this [10 year old Ruby project](https://github.com/emacsfodder/sublime2yas).

Like I mentioned above, I'm not sure if what I'm trying works with Ansible LSP, so perhaps it doesn't really work at all or there are practical concerns. And the snippets thing is actually working out, though I import them one collection at a time, customize them and remove what I don't need.

**Comment by dcunited001** [comment]
And having an example `ansible-language-server.Dockerfile` or something really helps for dependencies like these. 

Not everyone is running Ansible Tower.

**Pull request closed without merging**
