### PR TITLE
Allow use of Ansible files without a workspace

### PR DESCRIPTION
**Pull request by ganeshrn**
Fixes https://github.com/ansible/ansible-language-server/issues/117

*  If an individual file is opened in client without workspace (in
   case of VSCode) the workspace param in undefined
*  To allow completion to work explicity set the workspace to
   the folder containing the file opened within client.

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]
Thanks, it seems to be working nice.

**Comment by tomaciazek** [comment]
Nice workaround. But it could be improved a bit - if there is any open workspace for which the file's path is a subpath, that could be used instead. In any other case, the first open workspace could be used, since this is most likely going to be the intention of the user. Incidentally, this would also cover the case of _new, unsaved_ files, for which the path does not exist on the disk yet.

**Comment by ganeshrn** [comment]
@tomaciazek Thanks for the comment. 

>  But it could be improved a bit - the first open workspace could be used, since this is most likely going to be the intention of the user 

If the user opens the client with a single file (say from command-line `code <name-of-file>`) in that case there won't be any open workspace. I am not sure if I understood your comment clearly.

**Comment by tomaciazek** [comment]
> @tomaciazek Thanks for the comment.
> 
> > But it could be improved a bit - the first open workspace could be used, since this is most likely going to be the intention of the user
> 
> If the user opens the client with a single file (say from command-line `code <name-of-file>`) in that case there won't be any open workspace. I am not sure if I understood your comment clearly.

Alright, so I misunderstood the case that is being solved here. This solution will indeed be the best-effort implementation for that case. Mind that workspace created in this way will (likely) not provide any `ansible.cfg`, nor VS Code settings.

But, there are two other interesting cases, when there actually are some workspace folders to work with:
- newly opened file does not match any of them
- the user works on an unsaved tab
In both cases a better solution would be to take the first workspace from the list instead of generating a new one.

**Comment by webknjaz** [comment]
@tomaciazek could you explain those in more detail within separate issues so that this doesn't get lost?

**Pull request merged**
