### PR TITLE
Add defaults to settings section of README.md

### PR DESCRIPTION
**Pull request by mrolli**
Having the defaults in README.md might help people not familiar with code. One can see at first glance what is set by default and if changes are actually needed.

Having never used Typescript so far, I couldn't find the defaults for `ansible.ansibleNavigator.path` and `ansible.ansiblePlaybook.path`, but I guess it's the executable's name too as for ansible and ansible-lint. If so, I'm happy to add this, sqash and rebase if needed.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
In fact I think that the likely fix for this issue is to fully remove the section from this README file because the default values are not defined inside the code.

I searched for `ansibleNavigator` inside the codebase and failed to find anything, but we have it documented in that README.

If I am correct it would be up to the consumer of ALS to decide which defaults to use. For example the defaults for vscode-ansible can be seen at https://raw.githubusercontent.com/ansible/vscode-ansible/main/package.json

Also documenting defaults from the code inside the README will create bugs as I am almost sure we will fail to update the readme when we change the code and will likely confuse end-users that may end-up reading this page instead of reading the documentation of an IDE extension, with different defaults.

@tomaciazek @ganeshrn @priyamsahoo WDYT about that?  What is the right path to take here?

**Review by ganeshrn — APPROVED** [review]
Currently, the entries in the readme file for settings are manual and considering this we can extend it to manually update the default values. Going forward we can enhance the logic to update the settings section of readme automatically by reading the `package.json` file from this repo.

**Comment by ganeshrn** [comment]
> In fact I think that the likely fix for this issue is to fully remove the section from this README file because the default values are not defined inside the code.
> 
> I searched for `ansibleNavigator` inside the codebase and failed to find anything, but we have it documented in that README.
> 
> If I am correct it would be up to the consumer of ALS to decide which defaults to use. For example the defaults for vscode-ansible can be seen at https://raw.githubusercontent.com/ansible/vscode-ansible/main/package.json
> 
> Also documenting defaults from the code inside the README will create bugs as I am almost sure we will fail to update the readme when we change the code and will likely confuse end-users that may end-up reading this page instead of reading the documentation of an IDE extension, with different defaults.
> 
> @tomaciazek @ganeshrn @priyamsahoo WDYT about that? What is the right path to take here?



> In fact I think that the likely fix for this issue is to fully remove the section from this README file because the default values are not defined inside the code.
> 
> I searched for `ansibleNavigator` inside the codebase and failed to find anything, but we have it documented in that README.
> 
> If I am correct it would be up to the consumer of ALS to decide which defaults to use. For example the defaults for vscode-ansible can be seen at https://raw.githubusercontent.com/ansible/vscode-ansible/main/package.json
> 
> Also documenting defaults from the code inside the README will create bugs as I am almost sure we will fail to update the readme when we change the code and will likely confuse end-users that may end-up reading this page instead of reading the documentation of an IDE extension, with different defaults.
> 
> @tomaciazek @ganeshrn @priyamsahoo WDYT about that? What is the right path to take here?

If the setting section is removed from the readme doc how will the user come to know the settings that extension support w/o installing it on the marketplace?  I do agree with you comment that the actual settings in `package.json` and in readme file will soon be out of sync. We had a similar problem with `ansible-navigator` and it was solved by writing a utility that updated the docs automatically by parsing the argspec. It was later converted to sphinx extension by @webknjaz as part of this commit https://github.com/ansible/ansible-navigator/commit/90506d8dd3bb72b19b4945b6722a1f425e3a1691 
We can follow a similar approach here as well.

**Comment by ssbarnea** [comment]
@ganeshrn My impression is that you missed the most important bit: this is readme of ALS and user facing documentation is expected to be part of vscode-ansible project, not this one. I do not expect to see any user facing documentation in a development library that is designed to be used only by developers creating extensions.

**Comment by mrolli** [comment]
Ok, I see your perspecives. I'm coming from the neovim side and I'm trying to use the ansible language server with the built-in lsp client of neovim.

Meanwhile I found this section in the [lsp-config docs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ansiblels) and this is probably the documentation that I should have found first. @ssbarnea If you think that the lsp-config documentation is the place where this should be covered (in a more complete fashion), then I'm happy to improve their documentation with a PR and you may close this one unmerged.

**Comment by mrolli** [comment]
Ok, after having inspected their [wrapper](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/ansiblels.lua) that starts the language server standalone, their documentation is actually the place to outline the defaults the wrapper uses. They already link to your project, where the user then sees the whole list of available configuration settings (with defaults?). Anyway, sorry for causing headaches.

**Comment by ganeshrn** [comment]
> @ganeshrn My impression is that you missed the most important bit: this is readme of ALS and user facing documentation is expected to be part of vscode-ansible project, not this one. I do not expect to see any user facing documentation in a development library that is designed to be used only by developers creating extensions.

@ssbarnea The readme is also displayed on npm https://www.npmjs.com/package/@ansible/ansible-language-server and I think it is good info to have it in readme file. We will have same issue for https://github.com/ansible/vscode-ansible and it will be great if it can be solved in a uniform way.

**Comment by tomaciazek** [comment]
> In fact I think that the likely fix for this issue is to fully remove the section from this README file because the default values are not defined inside the code.

That's not true. See https://github.com/ansible/ansible-language-server/blob/2f8a17f1d5bd73442b7399379db151d8c01bb72d/src/services/settingsManager.ts#L15

A mechanism that synchronizes config with README would be nice, but I don't think we should remove the description from the manual, just because we don't have that yet.

**Comment by ganeshrn** [comment]
> A mechanism that synchronizes config with README would be nice, but I don't think we should remove the description from the manual, just because we don't have that yet.

Have raised an issue to track it https://github.com/ansible/ansible-language-server/issues/192

**Comment by ganeshrn** [comment]
Since the PR improves the README file as compared to what it is today in the main branch and there is a general consensus that we should keep the settings in readme file I will go ahead and merge this PR.

The work item to generate settings in README file can be tracked through issue https://github.com/ansible/ansible-language-server/issues/192

Till the feature is implemented the reviewer need to take care that the setting in code and readme are in sync.

@mrolli Thank you for your contribution!

**Pull request merged**
