### PR TITLE
Prepare 0.3.0 release

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
Please write the changelog consistently with the style of the rest of it. Per guidelines, it must describe what the high-level effect is for the end users.

**Comment by ssbarnea** [comment]
> Please write the changelog consistently with the style of the rest of it. Per guidelines, it must describe what the high-level effect is for the end users.

Why are you not writing these rephrasing yourself if they are so important? Do I need to remind you that this is a library and not something facing end-users.

My text was copied from https://github.com/ansible/vscode-ansible/releases as I did for years with molecule/lint and nobody complained about phrasing in changelog.

**Comment by webknjaz** [comment]
> PS. I would suggest reading previous entries, there is nothing consistent about them, so basically this change does not introduce any "inconsistencies".

The previous entries describe the past while what you add describes the future. This is inconsistent by definition.

**Review by cidrblock — APPROVED** [review]

**Review by webknjaz — CHANGES_REQUESTED** [review]
We've talked about this in the meetings many times already. I can fix this if you can't.

**Review by ganeshrn — APPROVED** [review]

**Pull request merged**
