### PR TITLE
Update module completion return statement to support FQCN

### PR DESCRIPTION
**Pull request by priyamsahoo**
- **The PR has the logic to support FQCN in module auto-completion.** Whenever `useFullyQualifiedCollectionName` is set to true (which by-default is), the user will get auto-completions for module names based on their FQCN.
For e.g., writing `ansible.builtin` would give suggestions for all the modules that are under the ansible.builtin collection namespace.

-  The auto-completion is smart enough to understand shortcuts while writing module names and provides the correct auto-completion accordingly.
For e.g., writing `ansiping` (or something similar) would give you `ansible.builtin.ping` as the first suggestion. Similarly, writing `iosping` (or similar) woould give you `cisco.ios.ping` as the first suggestion.

- Resolves https://github.com/ansible/vscode-ansible/issues/145

### CODE REVIEW

**Comment by ssbarnea** [comment]
If logic autocomplete no longer works when trying to type builtin modules without prefix I would be against this change.

While I am totally ok to always put the FQCN inside the files, I do also think that when using auto-complete our language server should be smart-enough to make the builtin implicit and add it when user presses enter. Example, typing "deb" should autocomplete with `ansible.builtin.debug`.

I still need to compile it locally and test it myself.

**Comment by tomaciazek** [comment]
> @tomaciazek We do want to encourage the use of full names, and the toggle is still there. I'm not sure I understand your remark here...
> 
> Are you suggesting an additional toggle after this goes in?

I'm not against full names, that default is already changed and the user will get FQCN with autocomplete. This PR, however, changes the sorting and filtering, so that collection namespaces and collection names will be matched and displayed first.

@priyamsahoo, your example is misleading - it only shows built-in `debug` first because it is a longer match. If there was a namespace or collection starting with `debu`, that would have been shown first.

The new toggle I propose would be to influence this sorting/filtering behavior.

**Comment by tomaciazek** [comment]
> The only change that happens with this PR now, is, the user will additionally be able to filter the suggestions based on FCQNs as well. In general scenario, filtration of suggestions should work as usual (as in the case when useFQCN is set to false).

1. That was always possible since `moduleFqcn` was part of the `filterText`.
2. Obviously, it is not the only thing changed here.

**Comment by ganeshrn** [comment]
> I actually really like the way it currently behaves, so that even if the FQCNs are best practice and should be placed in code, the user can just focus on writing the name of the actual component that he uses. And since that is a matter of personal preference, I'd suggest implementing a feature toggle (setting) for that.

Raised an issue to track configuring sort order https://github.com/ansible/ansible-language-server/issues/63

**Pull request merged**
