### PR TITLE
gha: prevent buid from passing if git reports dirty

### PR DESCRIPTION
**Pull request by ssbarnea**
This should prevent bugs where what we build is not the tracked
code or divergence between version inside package.json and
package-lock.json

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
I think this change is incorrect. `npm ci` should guard from this.

**Comment by ssbarnea** [comment]
> I think this change is incorrect. `npm ci` should guard from this.

In fact `npm ci` does not guard this in any way. That is why we end-up with this issue. I think that we have a similar test in https://github.com/ansible/vscode-ansible/blob/main/.github/workflows/ci.yaml#L98-L99 which works fine, but we missed to add one in ALS itself.

**Comment by webknjaz** [comment]
I know that it's present in the extension and I don't really like it. But it's rather pointless in this place, after running the commands specifically meant to modify the version in the metadata and the lockfile. Why do you think `npm pack` will modify the lockfile?

**Comment by webknjaz** [comment]
@ssbarnea instead of this, consider having a separate workflow that read the metadata and the lockfile with something like `jq` or `python -m json.tool` and compare the versions separately. Maybe that'll work. OTOH I'd rather just keep working on the workflow improvements (in my TODO list).

**Comment by ssbarnea** [comment]
> @ssbarnea instead of this, consider having a separate workflow that read the metadata and the lockfile with something like `jq` or `python -m json.tool` and compare the versions separately. Maybe that'll work. OTOH I'd rather just keep working on the workflow improvements (in my TODO list).

I would see that more complex and not being able to catch a wider range of problems. Another one that I know for sure was the reordering of package.json file. That change is simple and effective. In fact I used it in tox.ini in the past, for the same reason, preventing CI passes when tracked code was adulterated.

**Comment by webknjaz** [comment]
It is pointless because Git will never be dirty after a `git commit`.

**Comment by ssbarnea** [comment]
> It is pointless because Git will never be dirty after a `git commit`.

I think you are wrong here because the previous command, `npm pack` does implicitly run `npm ci` as part of prepack script. This has the effect of altering the content on `package-lock.json` if the bumping was incomplete. In fact that is what happened and why we failed to have a correct lock file.

Running `git dirty` at the end of almost any CI job is a good way of catching such bugs in workflow logic.

In fact I dislike our CI driver version bumping but that should be the subject of a different discussion. For the moment I am trying to prevent similar mistakes from slipping in again.

**Comment by webknjaz** [comment]
> I think you are wrong here because the previous command, `npm pack` does implicitly run `npm ci` as part of prepack script. This has the effect of altering the content on `package-lock.json` if the bumping was incomplete.

The whole point of the `npm ci` command is that it never changes the files if anything is inconsistent, it fails loudly. It's the key difference from `npm install`.

**Pull request closed without merging**
