### PR TITLE
Add support for nested module options (suboptions)

### PR DESCRIPTION
**Pull request by tomaciazek**
This implements the missing support for nested module options, including syntax highlighting, hover and completion.

I got inspired to implement it after talking with @priyamsahoo about potential solutions earlier this week.

### CODE REVIEW

**Review by ganeshrn — COMMENTED** [review]
Awesome!  Thanks for adding suboption completion support.

**Review by priyamsahoo — APPROVED** [review]
Thank you @tomaciazek :)

**Comment by ssbarnea** [comment]
@tomaciazek That is really cool. Would I ask too much to also include a test for this feature, just so we do not accidentally break it when me merge something else?

**Review by ssbarnea — APPROVED** [review]

**Comment by webknjaz** [comment]
@tomaciazek try creating feature branches in your fork next time so that you don't pollute the upstream with extra CI jobs + it makes the contributor experience better because they don't have differing branch versions when they fork the upstream.

**Pull request merged**
