### PR TITLE
Replace Number.MAX_SAFE_INTEGER with integer.MAX_VALUE

### PR DESCRIPTION
**Pull request by priyamsahoo**
It has been found that some of the clients of ALS do not support large integer values from the server responses and therefore they are unable to produce desired results in their extensions. One such scenario is in the case of diagnostics report sent by the server.

The PR fixes the issue by replacing `Number.MAX_SAFE_INTEGER [ value: 9007199254740991 (2^53 − 1) ]` with `integer.MAX_VALUE [ value:  2147483647 (2^31 - 1) ]`.

Fixes: #218

### CODE REVIEW

**Review by tomaciazek — APPROVED** [review]
Neat solution!

**Review by ganeshrn — APPROVED** [review]
Please add changelog fragments and tests as applicable.
Thank you!

**Comment by priyamsahoo** [comment]
> Please add changelog fragments and tests as applicable. Thank you!

Appropriate changes in the tests have been made in the PR.

**Review by ssbarnea — COMMENTED** [review]
Out of curiosity, why not using `-1` instead? It would be much easier to read than very long numbers.

**Comment by priyamsahoo** [comment]
> Out of curiosity, why not using `-1` instead? It would be much easier to read than very long numbers.

@ssbarnea, the idea here is to have a red squiggly line across the error line entirely.
Passing -1 to the character part in the range object does won't give the desired result. I have explained this here: https://github.com/ansible/ansible-language-server/pull/246#issuecomment-1064822691

**Comment by joshzcold** [comment]
@priyamsahoo  its working well in neovim, thank you 👍
you can see at the bottom of neovim your new number value from column being passed in.

https://user-images.githubusercontent.com/36175703/157906473-6956a591-3cea-4be7-add6-685118f6867d.mp4

**Pull request merged**
