### PR TITLE
Remove als acronym from docs website title

### PR DESCRIPTION
**Pull request by samccann**
ALS is an unfortunate acronym choice as it is also the acronym for a fatal disease (Lou Gehrig's disease).

Local tests shows this doesn't have to be abbreviated as the short title, this this PR.

### CODE REVIEW

**Comment by samccann** [comment]
How this looks now locally -
image

**Review by ssbarnea — APPROVED** [review]
While for documentation we can/should clearly avoid the alias we have some internal places where we cannot afford not to use an acronym due to constraints. Still, these are not user facing.

**Comment by samccann** [comment]
Yeah I realized that as I typed out ansible-language-server a few times in chat. It is long :-)  So I agree it doesn't need to be changed in other places.
...also, new to the project so not sure what's failing in CI?

**Comment by ssbarnea** [comment]
> Yeah I realized that as I typed out ansible-language-server a few times in chat. It is long :-) So I agree it doesn't need to be changed in other places. ...also, new to the project so not sure what's failing in CI?

Don't worry, there are unrelated to your change. As long docs job builds you are fine. 

PS. We are working on fixing the broken jobs but not all the changes can be implemented right away.

**Pull request merged**
