### PR TITLE
Use begin_column for end-range instead of MAX_SAFE_INTEGER for ansibleLint

### PR DESCRIPTION
**Pull request by joshzcold**
`Number.MAX_SAFE_INTEGER` passed into type `Range` produces unexpected results. 
9007199254740991 (int) => 9.007199254741e+15 (string)

This results in throwing errors on lsp clients not expecting a string. If it was an integer however I also feel like it would be unusable to the clients consider how big of a number it is.

Fixes: #218

### CODE REVIEW

**Comment by joshzcold** [comment]
This would solve issue: https://github.com/ansible/ansible-language-server/issues/218

**Review by ssbarnea — APPROVED** [review]
Looks legit, now you only need to add a changelog fragment for it. Please look at timeline protection job for details.

**Review by ganeshrn — APPROVED** [review]

**Comment by priyamsahoo** [comment]
Thanks for the change @joshzcold.

@ganeshrn, @ssbarnea, I think we should wait for the tests first and get it merged after we have the tests.

**Review by priyamsahoo — CHANGES_REQUESTED** [review]
Making change request to prevent merging it.

**Comment by joshzcold** [comment]
> Thanks for the change @joshzcold.
> 
> @ganeshrn, @ssbarnea, I think we should wait for the tests first and get it merged after we have the tests.

@priyamsahoo are you saying I need to create tests? Or do we have to wait for them to run and pass? thanks.

**Comment by priyamsahoo** [comment]
> > Thanks for the change joshzcold.
> > ganeshrn, ssbarnea, I think we should wait for the tests first and get it merged after we have the tests.
> 
> @priyamsahoo are you saying I need to create tests? Or do we have to wait for them to run and pass? thanks.

I am working on the tests for diagnostics and it is almost complete. Once that is merged, we can run your changes against the test and merge it.

**Comment by priyamsahoo** [comment]
@joshzcold, your changes are not the right solution for this issue: https://github.com/ansible/ansible-language-server/issues/218.
I can say this because with your changes, the red squiggly line for lint errors does not cover the entire line.

For eg.,
With your solution, the result is something like this:
ss2

Rather, the desired result should be like this:
ss1

I am working on this, and if you have a better approach feel free to update the PR.

**Comment by joshzcold** [comment]
@priyamsahoo thanks for testing.
It's possible max integer will work out if we can keep the type to int when it's passed into range.

But I'll see what I can find

**Comment by priyamsahoo** [comment]
@joshzcold, there is nothing wrong with the server's response and just to confirm, server sends that figure as an appropriate type (Number).
The error is because of how the neovim ansible extension (client) is dealing with the response.

In the case of vscode ansible extension, it works absolutely fine, even if the server sends some very large number ( like 10^308) that gets converted to scientific notations.

Still, to support such extensions, I have opened a new PR with appropriate changes: https://github.com/ansible/ansible-language-server/pull/261.

Please check and confirm if the PR's #261's changes are working or not.

**Pull request closed without merging**
