### PR TITLE
Add default tmp location for ansible

### PR DESCRIPTION
**Pull request by ganeshrn**
* Pass temp location variable within container pointing with the workdir so that ansible can create and write the temp files.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Can we get context on this? When/why it was not working?

I do not find the idea of polluting CWD with temp files but at the same time, I do know that at least on macos we would not be able to mount stuff from system temp, but i need to see what is the default ansible temp dir on mac.

Is that related to the fact the ansible builder container is broken due to  HOME != ~ ? Newer containers no longer have this issue.

**Comment by ganeshrn** [comment]
The CI failure will be fixed in a different PR by @priyamsahoo

**Comment by ganeshrn** [comment]
@ssbarnea Sorry I missed your review comment. 
> Is that related to the fact the ansible builder container is broken due to HOME != ~ ? Newer containers no longer have this issue.

Yes that's right. 

I can either revert this PR or fix any comments you have in another PR

**Comment by priyamsahoo** [comment]
CI failure fix: https://github.com/ansible/ansible-language-server/pull/463

**Comment by ganeshrn** [comment]
Reverted in PR https://github.com/ansible/ansible-language-server/pull/464

**Pull request merged**
