### PR TITLE
ci: use prettier on docs md files

### PR DESCRIPTION
**Pull request by ssbarnea**
Follow-Up: #215

Increases the scope of markdown files prettier will clean-up to include the docs directory and includes changes to those files made by prettier.

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
This seems to continue the tradition of not giving a darn about review requests like #177 but I'll still try. So I want to block this until #181 is reverted. Changing these linting settings was never discussed or accepted by the team.

**Review by cidrblock — APPROVED** [review]
Approving this based on the general philosophy that formatters free up time and CPU cycles so they can be used on user-facing features and resolving user-facing issues.

That said, I will defer to @tomaciazek @ganeshrn and @priyamsahoo here to decide if this gets merged.

**Comment by tomaciazek** [comment]
> This seems to continue the tradition of not giving a darn about review requests like #177 but I'll still try. So I want to block this until #181 is reverted. Changing these linting settings was never discussed or accepted by the team.

@ssbarnea, I agree with @webknjaz that you should have waited for his review before merging #181, as he did explicitly state opposition to these changes in #177.

>So I want to block this until https://github.com/ansible/ansible-language-server/pull/181 is reverted.

@webknjaz, are you saying that you'll approve this one once #177 is reverted? But that will inevitably break/change markdown files on every save, as explained in #177 ;)

@ssbarnea, @webknjaz could you please create a discussion similar to https://github.com/ansible-community/devtools/issues/28, where everyone can express their opinion in a well-structured format, since this is obviously a polarizing topic? The changes introduced here aren't urgent, so I don't see a reason not to take time to discuss them.

**Comment by webknjaz** [comment]
> are you saying that you'll approve this one once #181 is reverted?

I'm just saying that merging stuff with rejections or no reviews is a bad tone unless agreed offline. These things cascade and become harder to `git revert`, especially as new changes are made on top of that. The proper process would be re-submitting that and discussing the PR, including getting all the explanations necessary recorded.
I was merely calling this out because it's not up to the bar we want to hold ourselves to.

For now, I've lost interest in trying to review this as it doesn't feel like it'd matter anymore. This is why I'm just going to approve it.

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
